openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8082
    description: Generated server url
paths:
  /update/updateContact:
    put:
      tags:
        - endpoint-update-contact
      operationId: updateContact
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandUpdateContact'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseContactQuery'
  /contacts/email:
    put:
      tags:
        - endpoint-send-email-contact
      summary: Enviar correo
      operationId: sendEmail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandEmail'
        required: true
      responses:
        '200':
          description: Correo enviado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Contactp no encontrado
        '500':
          description: No se pudo procesar su solicitud.
  /contact/update/{id}:
    put:
      tags:
        - endpoint-update-contact-by-id
      operationId: searchContact
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandUpdateContact'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseListSearchContactQuery'
  /upload/file:
    post:
      tags:
        - endpoint-upload-file
      operationId: uploadTest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandUploadFile'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseUpdateFileQuery'
  /pass-phase:
    post:
      tags:
        - endpoint-pass-phase
      summary: pasar de fase a una persona
      operationId: passPhase
      parameters:
        - name: correo
          in: query
          required: true
          schema:
            type: string
        - name: faseEsperada
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Se hizo el engagement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: No se pudo hacer el engagement
        '500':
          description: No se pudo procesar su solicitud.
  /message-whatsapp/{email}:
    post:
      tags:
        - endpoint-send-message-whatsapp
      operationId: sendWhatsappMessage
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseVoid'
  /engagement:
    post:
      tags:
        - endpoint-engagement-contact
      summary: Crear un engagement
      operationId: createEngagement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandEngagement'
        required: true
      responses:
        '200':
          description: Se hizo el engagement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: No se pudo hacer el engagement
        '500':
          description: No se pudo procesar su solicitud.
  /createTask:
    post:
      tags:
        - endpoint-task-controller
      operationId: createTask
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandTask'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseTaskQuery'
  /createTask/by-list:
    post:
      tags:
        - endpoint-task-controller
      summary: Enviar notificación de inactividad de candidatos a talento
      operationId: createTaskByList
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CommandTask'
        required: true
      responses:
        '200':
          description: Notificaciones enviadas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Petición invalida
        '500':
          description: 'No se pudo procesar su solicitud. '
  /createNote:
    post:
      tags:
        - endpoint-note-controller
      operationId: createNote
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenericNote'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseEngagementQuery'
  /contacts/search-candidates:
    post:
      tags:
        - endpoint-search-contact
      summary: Buscar lista de candidatos
      operationId: searchContactsByList
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        '200':
          description: Candidatos encontrados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Candidatos no encontrados
        '500':
          description: 'No se pudo procesar su solicitud. '
  /clear-contact:
    post:
      tags:
        - endpoint-clear-contact-from-test
      summary: limpia un contacto y lo deja listo para pruebas
      operationId: clearContactoFromTest
      parameters:
        - name: correo
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Se hizo el engagement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: No se pudo hacer el engagement
        '500':
          description: No se pudo procesar su solicitud.
  /activity/approbe:
    post:
      tags:
        - endpoint-activity-approbe
      summary: aprueba una actividad de un contacto
      operationId: clearContactoFromTest_1
      parameters:
        - name: correo
          in: query
          required: true
          schema:
            type: string
        - name: estado
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Se hizo el engagement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: No se pudo hacer el engagement
        '500':
          description: No se pudo procesar su solicitud.
  /page/post/{blogPostId}:
    get:
      tags:
        - endpoint-search-page
      summary: Obtener un blog de hubspot
      operationId: searchPage
      parameters:
        - name: blogPostId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Blog obtenido con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '404':
          description: El blog de la vacante no se encontró
        '500':
          description: No se pudo procesar su solicitud.
  /owners/{id}:
    get:
      tags:
        - endpoint-search-by-id
      operationId: searchById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseOwnerQuery'
  /contacts/search:
    get:
      tags:
        - endpoint-search-contact
      summary: Buscar contact
      operationId: searchContact_1
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Encontro el contact
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: 'Contacto no encontrado '
        '500':
          description: 'No se pudo procesar su solicitud. '
  /business/submit-documentation-date:
    get:
      tags:
        - endpoint-submit-document-date
      summary: Retornar fecha de entrega de documentacion para contratacion
      operationId: getSubmitDocumentationDate
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Fecha encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: No se pudo procesar su solicitud.
  /business/search/{idBusiness}:
    get:
      tags:
        - endpoint-search-business
      summary: Buscar business
      operationId: search
      parameters:
        - name: idBusiness
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Negocio encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: No se pudo procesar su solicitud.
  /business/search-by-email/{email}:
    get:
      tags:
        - endpoint-search-business
      summary: Buscar negocio por email
      operationId: searchBusinessByEmail
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Negocio encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: No se pudo procesar su solicitud.
  /business/admission-date:
    get:
      tags:
        - endpoint-admission-date
      summary: Buscar fecha de admisión
      operationId: search_1
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Fecha encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: No se pudo procesar su solicitud.
  /blog/post/{blogPostId}:
    get:
      tags:
        - endpoint-search-blog-post
      summary: Obtener un blog de hubspot
      operationId: searchBlog
      parameters:
        - name: blogPostId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Blog obtenido con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '404':
          description: El blog de la vacante no se encontró
        '500':
          description: No se pudo procesar su solicitud.
components:
  schemas:
    CommandUpdateContact:
      type: object
      properties:
        email:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
    ContactQuery:
      type: object
      properties:
        properties:
          type: object
          additionalProperties:
            type: string
        id:
          type: integer
          format: int64
    GenericResponseContactQuery:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
          format: int32
        data:
          $ref: '#/components/schemas/ContactQuery'
    CommandEmail:
      type: object
      properties:
        to:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
    GenericResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
          format: int32
        data:
          type: object
    GenericResponseListSearchContactQuery:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
          format: int32
        data:
          type: array
          items:
            $ref: '#/components/schemas/SearchContactQuery'
    SearchContactQuery:
      type: object
      properties:
        properties:
          type: object
          additionalProperties:
            type: string
        id:
          type: integer
          format: int64
    CommandUploadFile:
      type: object
      properties:
        options:
          $ref: '#/components/schemas/Options'
        filename:
          type: string
        fileBase64:
          type: string
    Options:
      type: object
      properties:
        folderId:
          type: string
        access:
          type: string
    GenericResponseUpdateFileQuery:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
          format: int32
        data:
          $ref: '#/components/schemas/UpdateFileQuery'
    UpdateFileQuery:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        path:
          type: string
        url:
          type: string
        access:
          type: string
    GenericResponseVoid:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
          format: int32
        data:
          type: object
    CommandEngagement:
      type: object
      properties:
        email:
          type: string
        fileId:
          type: string
        body:
          type: string
    CommandDate:
      type: object
      properties:
        hour:
          type: string
        numDays:
          type: integer
          format: int32
    CommandTask:
      type: object
      properties:
        ownerId:
          type: string
        body:
          type: string
        priority:
          type: string
        status:
          type: string
        subject:
          type: string
        type:
          type: string
        dueDate:
          $ref: '#/components/schemas/CommandDate'
        dealId:
          type: string
        hsObjectId:
          type: string
    Association:
      type: object
      properties:
        id:
          type: string
        taskId:
          type: string
        dealId:
          type: string
    GenericResponseTaskQuery:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
          format: int32
        data:
          $ref: '#/components/schemas/TaskQuery'
    Task:
      type: object
      properties:
        id:
          type: string
        ownerId:
          type: string
        body:
          type: string
        priority:
          type: string
        status:
          type: string
        subject:
          type: string
        type:
          type: string
        timestamp:
          type: string
    TaskQuery:
      type: object
      properties:
        taskCreated:
          $ref: '#/components/schemas/Task'
        resultAssociation:
          $ref: '#/components/schemas/Association'
    GenericNote:
      type: object
      properties:
        email:
          type: string
        timestamp:
          type: string
        body:
          type: string
        ownerId:
          type: string
        attachmentIds:
          type: string
    EngagementQuery:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        dealId:
          type: string
        contactId:
          type: integer
          format: int64
    GenericResponseEngagementQuery:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
          format: int32
        data:
          $ref: '#/components/schemas/EngagementQuery'
    GenericResponseOwnerQuery:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
          format: int32
        data:
          $ref: '#/components/schemas/OwnerQuery'
    OwnerQuery:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
